FROM ubuntu:18.04

MAINTAINER Choi, Seunghee <shcho852@gmail.com>

## Omit user input
ENV DEBIAN_FRONTEND=noninteractive

## Update
RUN apt-get update 

## Install Default App 
RUN apt-get -y install vim curl git wget locales 

## PHP-FPM7.3 Version Install and Setup
RUN apt-get install -y software-properties-common && apt-add-repository ppa:ondrej/php \
 && apt update \
 && apt-get -y install php7.3-fpm php7.3-mysql php7.3-redis && rm -rf /run/php && mkdir /run/php

RUN sed -i "s/listen =/;listen =/g" /etc/php/7.3/fpm/pool.d/www.conf \
 && sed -i'' -r -e "/;listen = \/run\/php\/php7.3-fpm.sock/a\listen = services_php_fpm_1:9000" /etc/php/7.3/fpm/pool.d/www.conf \
 && sed -i "s/;date.timezone =/date.timezone = Asia\/Seoul/g"  /etc/php/7.3/cli/php.ini \
 && sed -i "s/;date.timezone =/date.timezone = Asia\/Seoul/g"  /etc/php/7.3/fpm/php.ini

## PHP redis Setup
RUN sed -i "s/session.save_handler = files/session.save_handler = redis/g" /etc/php/7.3/fpm/php.ini \
 && sed -i'' -r -e "/;session.save_path = \"\/var\/lib\/php\/sessions\"/a\session.save_path = \"tcp:\/\/services_redis_1:6379\"" /etc/php/7.3/fpm/php.ini \
 && sed -i "s/session.save_handler = files/session.save_handler = redis/g" /etc/php/7.3/cli/php.ini \
 && sed -i'' -r -e "/;session.save_path = \"\/var\/lib\/php\/sessions\"/a\session.save_path = \"tcp:\/\/services_redis_1:6379\"" /etc/php/7.3/cli/php.ini


## locales Setting
ENV LANG ko_KR.UTF-8
ENV LANGUAGE ko_KR.UTF-8
RUN locale-gen ko_KR ko_KR.UTF-8
RUN update-locale LANG=ko_KR.UTF-8

EXPOSE 9000 

COPY ./app/info.php /html/
COPY ./app/db.php /html/
COPY ./app/blog_manage_pdo.php /html/
COPY ./app/login.php /html/
COPY ./app/login_proc.php /html/
COPY ./app/logout.php /html/
COPY ./app/management_pdo.php /html/

CMD ["php-fpm7.3", "-F"]
